// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNooantGMwK5MUvqLAfu4oSFyWk3OGENM',
    appId: '1:1048472890286:web:edd7910bc1bcd58eb9f63f',
    messagingSenderId: '1048472890286',
    projectId: 'football-iq-2da71',
    authDomain: 'football-iq-2da71.firebaseapp.com',
    storageBucket: 'football-iq-2da71.firebasestorage.app',
    measurementId: 'G-E6CGLGC9J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2uxIp-ZKbHzVU33PKA3i5kETbULv0Jv0',
    appId: '1:1048472890286:android:4a0c4b5e9ace0854b9f63f',
    messagingSenderId: '1048472890286',
    projectId: 'football-iq-2da71',
    storageBucket: 'football-iq-2da71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChhi_57Ry9JQFzXGc6_b86kJrUHTSuVq8',
    appId: '1:1048472890286:ios:2c0b775079da1548b9f63f',
    messagingSenderId: '1048472890286',
    projectId: 'football-iq-2da71',
    storageBucket: 'football-iq-2da71.firebasestorage.app',
    iosBundleId: 'io.codeexplorer.footballIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChhi_57Ry9JQFzXGc6_b86kJrUHTSuVq8',
    appId: '1:1048472890286:ios:2c0b775079da1548b9f63f',
    messagingSenderId: '1048472890286',
    projectId: 'football-iq-2da71',
    storageBucket: 'football-iq-2da71.firebasestorage.app',
    iosBundleId: 'io.codeexplorer.footballIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNooantGMwK5MUvqLAfu4oSFyWk3OGENM',
    appId: '1:1048472890286:web:ebb62b141c660988b9f63f',
    messagingSenderId: '1048472890286',
    projectId: 'football-iq-2da71',
    authDomain: 'football-iq-2da71.firebaseapp.com',
    storageBucket: 'football-iq-2da71.firebasestorage.app',
    measurementId: 'G-TX08N61VSQ',
  );
}
